version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_checkout:
        # Use `git log` to check if the latest commit contains "skip ci",
        # in that case exit the command with 183 to cancel the build
        - (git --no-pager log --pretty="tformat:%s -- %b" -1 | grep -viq "skip docs") || exit 183


conda:
  environment: .rtd-environment.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/conf.py

formats: []
